language: objective-c
osx_image: xcode8.3
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -project "FileVaultCracker.xcodeproj" -scheme "FileVaultCracker" build analyze | xcpretty
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
